####### job setting ########
cluster: condor
container_image: osdf:///igwn/cit/staging/yumeng.xu/images/pycwb/pycwb-v0.31.0.dev13.sif
accounting_group: ligo.dev.o4.burst.allsky.cwboffline
job_per_worker: 1
job_memory: 8GB
job_disk: 10GB

# chunk_id: {{ CHUNK_ID }}

# plot_trigger: True
save_cluster: False

analysis: "2G"
cfg_search: "r"

optim: False

###### network configuration ######
ifo: {{ IFO_SHORT_NAME }}
refIFO: {{ REF_IFO_SHORT_NAME }}

inRate: 16384
# lags
lagSize: 1
lagStep: 1.
lagOff: 0
lagMax: 1

# superlags
slagSize: 2 
slagMin: 0
slagMax: 2
slagOff: 0

# job
segLen: 1200
segMLS: 1200
segTHR: 200
segEdge: 10

# frequency
fLow: 16.
fHigh: 2048.


levelR: 2
l_low: 3 # low frequency resolution level		// std (sthr = 2)
l_high: 9 # high frequency resolution level	// std (sthr = 8)

wdmXTalk: "wdmXTalk/OverlapCatalog-ilLev3-hLev9-iNu6-P10.xbin"

healpix: 5

###### cWB production thresholds & regulators ######

bpp: 0.001
subnet: 0.4
subcut: -1.0
subrho: 4.5
subnorm: 2.5
select_subrho: 4.5
netRHO: -6.5
cedRHO: 6.5
l_white: 10
netCC: 0.5
Acore: 1.7
Tgap: 0.2
Fgap: 640.0
delta: 0.5
cfg_gamma: -1.0
LOUD: 300

pattern: 10
Search: 'CBC'

# simulation
# simulation: None
nfactor: 1

###### injection settings ######

injection:
  seed: 16
  parameters_from_python:
    function: "./input/injection_parameters.get_injection_parameters"
    args:
      seed: 16
  generator: "burst_waveform.interface.generate_waveform_pycwb.get_td_waveform"
  repeat_injection: 1
  sky_distribution:
    type: UniformAllSky
  time_distribution:
    type: 'rate'
    rate: 1/200
    jitter: 30

###### job segments ######

gps_start: {{ CHUNK_START }}
gps_end: {{ CHUNK_END }}

channelNamesRaw: {{ CHANNELNAMES_RAW }}

{% if GWDATAFIND %}
gwdatafind:
  site: {{ GWDATAFIND.site }}
  frametype: {{ GWDATAFIND.frametype }}
  host: "{{ GWDATAFIND.host }}"
  urltype: "{{ GWDATAFIND.urltype }}"
{% endif %}
{% if FRFILES %}
frFiles: {{ FRFILES }}
{% endif %}

DQF: {{ DQF }}
