version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: envs/environment.yml
#  commands:
#    - wget -q https://root.cern/download/root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
#    - tar -xf root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz --strip-components=1 -C /usr/local/
#    - export ROOTSYS=/usr/local
#    - export PYTHONPATH=$ROOTSYS/lib:$PYTHONPATH
#    - export CLING_STANDARD_PCH=none
#    - apt-get update
#    - apt-get -y install git dpkg-dev cmake pkg-config g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev tar gfortran subversion
#    - apt-get -y install libfftw3-dev libcfitsio9 libsharp0 python3-pip
#    - wget -q http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
#    - dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
#    - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/libhealpix-cxx3_3.80.0-5_amd64.deb
#    - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/libhealpix-cxx-dev_3.80.0-5_amd64.deb
#    - dpkg -i libhealpix-cxx3_3.80.0-5_amd64.deb
#    - dpkg -i libhealpix-cxx-dev_3.80.0-5_amd64.deb
#    - apt-get -y install python3-pip python3-venv
#    - ln -s /usr/bin/python3 /usr/bin/python
#    - python3 -m pip install pip setuptools -U

python:
  install:
    #- requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

#environment:
#  ROOTSYS: /usr/local
#  PYTHONPATH: /usr/local/lib:$PYTHONPATH

#apt_packages:
#  - wget
#  - cmake
#  - g++
#  - gcc
#  - gfortran
#  - libx11-dev
#  - libxpm-dev
#  - libxft-dev
#  - libxext-dev
#  - libfftw3-dev
#  - libcfitsio9
#  - libsharp0
#  - libssl1.1
#
#pre_build:
#  - wget -q https://root.cern/download/root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz
#  - tar -xf root_v6.26.14.Linux-ubuntu22-x86_64-gcc11.4.tar.gz --strip-components=1 -C /usr/local/
#  - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/libhealpix-cxx3_3.80.0-5_amd64.deb
#  - wget -q https://launchpad.net/ubuntu/+archive/primary/+files/libhealpix-cxx-dev_3.80.0-5_amd64.deb
#  - dpkg -i libhealpix-cxx3_3.80.0-5_amd64.deb
#  - dpkg -i libhealpix-cxx-dev_3.80.0-5_amd64.deb
#
#exclude:
#  - "dist/*"
#  - "*.tar.gz"
#  - "*.deb"