"""Independent cWB getTDvecSSE fixture, including delays beyond one TF bin.

Generated by runs/core_pixel_debug/delay_fixture.C with cWB 6.4.6.9.
The fixture exports TF planes and actual SSE outputs at both time parities,
interior/edge bands, and delays -329..329 (J=64, TDSize=12).
"""
from pathlib import Path

import numpy as np
from wdm_wavelet.wdm import WDM
from pycwb.types.td_batch_inputs import TDBatchInputs


def test_native_vectors_match_cwb_sse_fixture():
    with np.load(Path(__file__).parent / 'data/cwb_sse_delay_fixture.npz') as fixture:
        planes = fixture['planes']
        indices = fixture['indices']
        expected = fixture['expected']
        half_range = int(fixture['K'])
    wavelet = WDM(M=16, K=16, beta_order=6, precision=10)
    wavelet.set_td_filter(12, 4)
    filters = wavelet.td_filters
    inputs = TDBatchInputs(
        np.pad(planes[0], ((12, 12), (0, 0))),
        np.pad(planes[1], ((12, 12), (0, 0))),
        filters.T0, filters.Tx, 16, 12, 64,
    )
    actual = inputs.extract_td_vecs(indices, half_range)
    np.testing.assert_allclose(actual, expected, atol=8e-7, rtol=3e-7)
