"""Generic workflow report page that composes artifacts from prior actions."""

from __future__ import annotations

import html
import json
import os
import shutil
from typing import Any, Optional

from pycwb.post_production.action_spec import action_spec


def _resolve(work_dir: str, path: str) -> str:
    return path if os.path.isabs(path) else os.path.join(work_dir, path)


def _copy_asset(
    work_dir: str,
    output_dir: str,
    path: str,
    index: int,
) -> str:
    source = _resolve(work_dir, path)
    if not os.path.exists(source):
        raise FileNotFoundError(f"Report asset not found: {source}")
    assets_dir = os.path.join(output_dir, "assets")
    os.makedirs(assets_dir, exist_ok=True)
    basename = f"{index:02d}_{os.path.basename(source)}"
    destination = os.path.join(assets_dir, basename)
    if os.path.abspath(source) != os.path.abspath(destination):
        shutil.copy2(source, destination)
    return os.path.relpath(destination, output_dir).replace(os.sep, "/")


def _render_page(
    title: str,
    subtitle: str,
    plots: list[dict[str, Any]],
    metadata: Optional[dict[str, Any]],
) -> str:
    plot_sections = []
    for plot in plots:
        plot_sections.append(
            '<section class="plot-section">'
            f"<h2>{html.escape(str(plot['title']))}</h2>"
            f"<p>{html.escape(str(plot.get('description', '')))}</p>"
            f'<iframe src="{html.escape(plot["href"])}" '
            f'title="{html.escape(str(plot["title"]))}" '
            f'height="{int(plot.get("height", 620))}" loading="lazy" '
            'sandbox="allow-scripts allow-same-origin"></iframe>'
            "</section>"
        )
    metadata_html = ""
    if metadata:
        metadata_html = (
            '<details><summary>Report metadata</summary><pre>'
            + html.escape(json.dumps(metadata, indent=2, sort_keys=True))
            + "</pre></details>"
        )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
    :root {{ color-scheme: light dark; --bg: #ffffff; --fg: #17202a; --muted: #5f6b76; --panel: #f6f8fa; --border: #d0d7de; }}
    @media (prefers-color-scheme: dark) {{ :root {{ --bg: #0d1117; --fg: #e6edf3; --muted: #9da7b3; --panel: #161b22; --border: #30363d; }} }}
    * {{ box-sizing: border-box; }}
    body {{ margin: 0; background: var(--bg); color: var(--fg); font-family: system-ui, sans-serif; line-height: 1.45; }}
    main {{ width: min(1500px, 100%); margin: 0 auto; padding: 24px; }}
    header {{ margin-bottom: 22px; }}
    h1, h2 {{ font-weight: 500; }}
    h1 {{ margin: 0 0 4px; font-size: clamp(1.5rem, 3vw, 2.25rem); }}
    h2 {{ margin: 0 0 6px; font-size: 1.2rem; }}
    p {{ color: var(--muted); margin: 0 0 12px; }}
    section {{ margin: 0 0 24px; }}
    iframe {{ width: 100%; border: 1px solid var(--border); border-radius: 8px; background: var(--panel); }}
    details {{ margin-top: 18px; }}
    pre {{ white-space: pre-wrap; color: var(--muted); }}
    @media (max-width: 600px) {{ main {{ padding: 14px; }} iframe {{ height: 520px; }} }}
  </style>
</head>
<body>
<main>
  <header><h1>{html.escape(title)}</h1><p>{html.escape(subtitle)}</p></header>
  {''.join(plot_sections)}
  {metadata_html}
</main>
</body>
</html>
"""


@action_spec(
    outputs=["output_file"],
    inputs=["plots"],
    display_name="Generic web report",
    description="Compose interactive plot artifacts from previous actions into one page",
    help=(
        "Each plot entry supplies title, html_file, optional description, and "
        "height. Assets are copied beside the report and embedded as interactive "
        "iframes. The action is intentionally analysis-agnostic."
    ),
)
def generic_web_report(
    work_dir: str,
    plots: list[dict[str, Any]],
    title: str = "pycWB postproduction report",
    subtitle: str = "Interactive products generated by the postproduction workflow.",
    output_file: str = "public/generic_report/index.html",
    metadata: Optional[dict[str, Any]] = None,
    **kwargs,
) -> dict[str, Any]:
    """Build one portable page from interactive HTML plots produced upstream."""
    if not plots:
        raise ValueError("plots must contain at least one HTML plot artifact")
    work_dir = os.path.abspath(str(work_dir))
    output_path = _resolve(work_dir, output_file)
    output_dir = os.path.dirname(output_path) or "."
    os.makedirs(output_dir, exist_ok=True)

    copied = []
    for index, plot in enumerate(plots):
        source = plot.get("html_file") or plot.get("path") or plot.get("file")
        if not source:
            raise ValueError(f"Plot entry {index} is missing html_file/path/file")
        copied.append({
            **plot,
            "title": plot.get("title") or os.path.basename(str(source)),
            "href": _copy_asset(work_dir, output_dir, str(source), index),
        })

    page = _render_page(
        title=str(title),
        subtitle=str(subtitle),
        plots=copied,
        metadata=metadata,
    )
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write(page)
    return {
        "output_file": output_path,
        "n_plots": len(copied),
        "assets": [plot["href"] for plot in copied],
    }


__all__ = ["generic_web_report"]
