# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.8.3.dev0+gf6d73a1.d20230306'
__version_tuple__ = version_tuple = (0, 8, 3, 'dev0', 'gf6d73a1.d20230306')
