# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.10.1.dev0+g6ffc393.d20230308'
__version_tuple__ = version_tuple = (0, 10, 1, 'dev0', 'g6ffc393.d20230308')
