name: pycwb
channels:
  - conda-forge
  - igwn
dependencies:
  - cmake
  - healpix_cxx=3.81
  - lalsuite
  - nds2-client
  - pkg-config
  - python-nds2-client
  - python=3.10
  - root=6.26.10
  - setuptools_scm
  - sphinx_rtd_theme
  - furo