name: pycwb
channels:
  - conda-forge
  - igwn
dependencies:
  - lalsuite
  - nds2-client
  - python-nds2-client
  - python=3.13
  - pip
  - setuptools_scm
  - pip:
      - sphinxawesome-theme==6.0.5
