from pathlib import Path
from types import SimpleNamespace
import numpy as np
import pytest
from pycwb.modules.data_conditioning.resampling import meyer_downsample, uses_cwb_snr_resampling

@pytest.mark.parametrize('level',[1,3])
def test_cwb_exported_meyer_layers(level):
    # cWB 6.4.6.9 Meyer(1024), generated by runs/lf_sim_corrected/meyer_fixture.C
    with np.load(Path(__file__).parent/'data/cwb_meyer_fixture.npz') as d:
        np.testing.assert_allclose(meyer_downsample(d['input'],level),d[f'level{level}'],atol=2e-14,rtol=2e-14)

def test_reference_mode_only_changes_target_snr_trials():
    c=SimpleNamespace(injection_resampling='cwb')
    assert uses_cwb_snr_resampling(c,[{'target_snr':10}])
    assert not uses_cwb_snr_resampling(c,[{'hrss':1e-22}])
    assert uses_cwb_snr_resampling(SimpleNamespace(),[{'target_snr':10}])
    assert not uses_cwb_snr_resampling(SimpleNamespace(injection_resampling='fft'),[{'target_snr':10}])
    with pytest.raises(ValueError,match='separate trials'):
        uses_cwb_snr_resampling(c,[{'target_snr':10},{'hrss':1e-22}])


def test_final_injection_resampling_preserves_epoch_and_reference_amplitude():
    from pycwb.modules.data_conditioning.resampling import resample_snr_injection
    from pycwb.types.time_series import TimeSeries
    config = SimpleNamespace(inRate=16384, fResample=0, levelR=3, dcCal=[7.0])
    with np.load(Path(__file__).parent/'data/cwb_meyer_fixture.npz') as fixture:
        original = fixture['input'].copy()
        signal = TimeSeries(original.copy(), dt=1/config.inRate, t0=1234567890.)
        result = resample_snr_injection(signal, config)
        np.testing.assert_allclose(result.data, fixture['level3'], atol=2e-14, rtol=2e-14)
        np.testing.assert_array_equal(signal.data, original)
    assert result.sample_rate == config.inRate / 8
    assert result.t0 == signal.t0


def test_schema_and_runtime_defaults_select_cwb_for_snr_only():
    from pycwb.constants.user_parameters_schema import schema
    assert schema['properties']['injection_resampling']['default'] == 'cwb'
    default = SimpleNamespace()
    assert uses_cwb_snr_resampling(default, [{'targeted_snr': 10}])
    assert not uses_cwb_snr_resampling(default, [{'hrss': 1e-22}])
    assert not uses_cwb_snr_resampling(default, [])
    with pytest.raises(ValueError, match='separate trials'):
        uses_cwb_snr_resampling(default, [{'target_snr': 10}, {'hrss': 1e-22}])
