H1_cat0:
  type: CWB_CAT0
  inverted: False
  column4: False
H1_cat1:
  type: CWB_CAT1
  inverted: True
  column4: False
H1_cat2:
  type: CWB_CAT2
  inverted: True
  column4: False
H1_cat4:
  type: CWB_CAT4
  inverted: True
  column4: False
L1_cat0:
  type: CWB_CAT0
  inverted: False
  column4: False
L1_cat1:
  type: CWB_CAT1
  inverted: True
  column4: False  
L1_cat2:
  type: CWB_CAT2
  inverted: True
  column4: False
L1_cat4:
  type: CWB_CAT4
  inverted: True
  column4: False
V1_cat0:
  type: CWB_CAT0
  inverted: False
  column4: False
V1_cat1:
  type: CWB_CAT1
  inverted: True
  column4: False  
V1_cat4:
  type: CWB_CAT4
  inverted: True
  column4: False
