from pathlib import Path
from types import SimpleNamespace
import numpy as np
import pytest
from pycwb.modules.injection.resampling import meyer_downsample, uses_cwb_snr_resampling

@pytest.mark.parametrize('level',[1,3])
def test_cwb_exported_meyer_layers(level):
    # cWB 6.4.6.9 Meyer(1024), generated by runs/lf_sim_corrected/meyer_fixture.C
    with np.load(Path(__file__).parent/'data/cwb_meyer_fixture.npz') as d:
        np.testing.assert_allclose(meyer_downsample(d['input'],level),d[f'level{level}'],atol=2e-14,rtol=2e-14)

def test_reference_mode_only_changes_target_snr_trials():
    c=SimpleNamespace(injection_resampling='cwb')
    assert uses_cwb_snr_resampling(c,[{'target_snr':10}])
    assert not uses_cwb_snr_resampling(c,[{'hrss':1e-22}])
    assert not uses_cwb_snr_resampling(SimpleNamespace(),[{'target_snr':10}])
    with pytest.raises(ValueError,match='separate trials'):
        uses_cwb_snr_resampling(c,[{'target_snr':10},{'hrss':1e-22}])
