"""Reference arrays exported by the original cWB code, not generated by the test."""
import json
from pathlib import Path
from unittest.mock import patch
import numpy as np
import pytest
from pycwb.modules.injection.burst_population import get_td_waveform

FIXTURE=Path(__file__).with_name('data')/'cwb_hf_waveform_fixture.npz'
with np.load(FIXTURE,allow_pickle=False) as data:
    CASES=json.loads(str(data['cases_json']))

@pytest.mark.parametrize('case',CASES,ids=[q['key'] for q in CASES])
def test_polarizations_against_original_cwb(case):
    p=case['parameters'];key=case['key']
    with np.load(FIXTURE,allow_pickle=False) as data:
        class ReferenceGaussian:
            def __init__(self,seed):
                self.component='pseed' if seed==p['pseed'] else 'xseed'
            def normal(self,size):
                samples=data[key+'_'+self.component]
                assert len(samples)==size
                return samples.copy()
        if p['approximant']=='WNB':
            with patch('numpy.random.default_rng',side_effect=ReferenceGaussian):
                generated=get_td_waveform(**p)
        else:
            generated=get_td_waveform(**p)
        hp,hc=data[key+'_hp'].copy(),data[key+'_hx'].copy()
        scale=p['hrss']/np.sqrt((hp@hp+hc@hc)/16384.)
        if p['approximant']=='SGE':
            hp*=(1+np.cos(p['iota'])**2)/2
            hc*=np.cos(p['iota'])
        for component,reference in [('hp',hp*scale),('hc',hc*scale)]:
            error=np.linalg.norm(generated[component].data-reference)/np.linalg.norm(reference)
            assert error<1e-12
